### ISSUE TITLE
[Feature request] Allow to combine with github actions

### ISSUE THREAD

**Issue by TheZoker** [OctoPrint/OctoPrint-FirmwareUpdater#102]
I don't know if that is a good idea, but my plan is the following:
I have a fork of marlin, where I have my own configuration as a commit and rebase it regularly (to keep it up2date with the marlin repo).
All these changes are automatically tested via the new github actions (so essentially: `platformio run build`).
Now my idea is, if the build was successfully, the new firmware should be uploaded to octroprint and flashed automatically to the printer. That would save me a lot of time (basically that`s continuous deployment).
So a step within the actions could look like:
```
...
      - id: build
        name: Build
        run: platformio run
      - id: auto_flash
        name: Automatically flash firmware
        uses: OctoPrint/action-octoprint@1.0.0
        env:
          OCTOPRINT_IP: ${{ secrets.OCTOPRINT_IP }}
          OCTOPRINT_API_KEY: ${{ secrets.OCTOPRINT_API_KEY }}
        if: job.steps.build.status == success
...
```

So with that, every time I rebase my config onto the latest marlin firmware and it builds successfully, the firmware will be updated automatically. 

And in combination with this plugin, this would be fantastic. 
So the request would be:
- Allow to upload firmware to octoprint from action
- Allow to flash this firmware remotely (secured with the API key)
